# Generated by Django 4.1.7 on 2023-04-02 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('desciption', models.CharField(max_length=50)),
                ('course_level', models.CharField(choices=[('A1', 'begginer'), ('A2', 'Elementary'), ('B1', 'pre-intermedia'), ('B2', 'Intermedia')], max_length=50)),
                ('course_duration', models.IntegerField(choices=[(2, '2 month'), (4, '4 months'), (6, '6 months'), (6, '6 months')])),
                ('fee', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('enrollment_date', models.DateField(max_length=50)),
                ('birthday', models.DateField(max_length=50)),
                ('group_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=50)),
                ('hire_date', models.DateField(max_length=50)),
                ('birthday', models.DateField(max_length=50)),
                ('group_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_per_week', models.CharField(max_length=50)),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('location', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbeng.course')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(auto_now=True)),
                ('payment_amount', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbeng.student')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=50)),
                ('material_description', models.TextField()),
                ('material_link', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbeng.course')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.CharField(choices=[(2, 'poor'), (3, 'Satisfactory'), (4, 'good'), (5, 'excellent')], max_length=50)),
                ('grade_day', models.DateField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbeng.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbeng.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendace_day', models.DateField(auto_now=True)),
                ('attendace_status', models.CharField(choices=[(0, 'absence'), (1, 'present')], max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbeng.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbeng.student')),
            ],
        ),
    ]
