# Generated by Django 4.1.7 on 2023-04-02 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbeng', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='group_name',
        ),
    ]
