# Generated by Django 4.1.7 on 2023-04-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeng', '0003_alter_teacher_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendace',
            name='attendace_status',
            field=models.CharField(choices=[('-', 'absence'), ('+', 'present')], max_length=50),
        ),
    ]
