# Generated by Django 4.1.7 on 2023-05-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeng', '0011_alter_schedule_end_time_alter_schedule_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.RenameModel(
            old_name='Attendace',
            new_name='Attendance',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='attendace_day',
            new_name='attendance_day',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='attendace_status',
            new_name='attendance_status',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='desciption',
            new_name='description',
        ),
    ]
