# Generated by Django 4.1.7 on 2023-05-01 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbeng', '0012_user_rename_attendace_attendance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group_name',
        ),
    ]
