# Generated by Django 4.1.7 on 2023-05-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbeng', '0013_remove_student_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.AddField(
            model_name='course',
            name='members',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
