# Generated by Django 4.1.7 on 2023-05-31 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbeng', '0016_alter_payment_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbeng.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbeng.student')),
            ],
        ),
    ]
